# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot = {
      initrd = {
        availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" ];
        kernelModules = [ ];
      };
      kernelModules = [ "kvm-intel" ];
      extraModulePackages = [ ];
    };

    fileSystems = {
      "/" =
        { device = "zpool/root";
        fsType = "zfs";
      };

      "/etc" =
        { device = "zpool/etc";
        fsType = "zfs";
        neededForBoot = true;
      };

      "/var" =
        { device = "zpool/var";
        fsType = "zfs";
      };

      "/nix" =
        { device = "zpool/nix";
        fsType = "zfs";
      };

      "/nix/store" =
        { device = "/nix/store";
        fsType = "none";
        options = [ "bind" ];
      };

      "/home" =
        { device = "zpool/home";
        fsType = "zfs";
      };

      "/boot" =
        { device = "/dev/disk/by-uuid/8207-93D2";
        fsType = "vfat";
      };
    };


  swapDevices =
    [ { device = "/dev/disk/by-uuid/81c2908b-8fd6-493c-8092-e6541d5d72b7"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wg-mullvad.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp170s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
