#!/bin/bash

# You can call this script like this:
# volumecontrol up
# volumecontrol down
# volumecontrol mute

function get_volume {
    sys volume get
}

case $1 in
    up)
	# Set the volume on (if it was muted)
	amixer set Master on > /dev/null
	# Up the volume (+ 2%)
	amixer sset Master 2%+ > /dev/null
	send_notification
	canberra-gtk-play -i audio-volume-change
	;;
    down)
	amixer set Master on > /dev/null
	amixer sset Master 2%- > /dev/null
	send_notification
	canberra-gtk-play -i audio-volume-change
	;;
    mute)
    	# Toggle mute
	amixer set Master 1+ toggle > /dev/null
	;;
    *)
	volume="$(get_volume)"

	if [[ $volume == "100" ]]; then
		icon=""
	elif [[ $volume -ge "89" && $volume -le "100" ]]; then
		icon=""
	elif [[ $volume -ge "79" && $volume -le "90" ]]; then
		icon=""
	elif [[ $volume -ge "69" && $volume -le "80" ]]; then
		icon=""
	elif [[ $volume -ge "59" && $volume -le "70" ]]; then
		icon=""
	elif [[ $volume -ge "49" && $volume -le "60" ]]; then
		icon=""
	elif [[ $volume -ge "39" && $volume -le "50" ]]; then
		icon=""
	elif [[ $volume -ge "29" && $volume -le "40" ]]; then
		icon=""
	elif [[ $volume -ge "19" && $volume -le "30" ]]; then
		icon=""
	elif [[ $volume -ge "9" && $volume -le "20" ]]; then
		icon=""
	elif [[ $volume -gt "0" && $volume -le "10" ]]; then
		icon=""
	elif [[ $volume -eq "0" ]]; then
		icon=""
		volume="M "
	fi


if is_mute; then
		icon=""
		volume="M "
fi

printf "%s" "$icon $volume%"
  ;;
esac
