gpg:
    primary:
        key: ENC[AES256_GCM,data:BYcdrtx274R+5XAcr+pq2oP+3A26o8uWpDpw+r34fCryz0k8mdqWzg==,iv:QUhFv4ZrgH34nhXmvX6jTE0WWR276c6miP1TeDAUx0I=,tag:xvywRkXfy0ekKrOTIiaN1g==,type:str]
        content: ENC[AES256_GCM,data:iRbgehWT4xqDVvzmtl7ZcEC26jLi38+gWy/1nt6tFrSU9OcDiSxseOHu8+1GWTTVQu/eQQcLLDL16ZGll/8+poXr//y2YLogYr9ieZw/EztQx3ATNrb4gqz3h5MT2+eQBoPY69wmPu9XEUjpk6zkDQO3NZUrKGzJYQNwbk/GLAflmCevCL+Ph8/lMf5h+Yf1/tc9SRqgeJsYMsIT9gqNupGLbirOWOkLdiKWwVl7b6v8SLm6lq2CfarW2+ct8U1FSxUQkZZW/D7eEaJ6pGI6lkUn2moo9ITo+h0+CIpCLSWt0IGGsVcgQWOGfOZQy5gjjrn7Os5xvBO+F7AiMwN6qlnVYuv9qGtO4XE9a787v+hNYFsSu2FGw+4ev5kfW+oTfVc99lEbrLJ5ClC8yuOTw/jEbb1moi8gNawF0eH9u6PeTaXjXPHGcxmqe19SjmbcgIAxDlVCjnUnlzeRH7VIjdUEIlaO8jI9kHuFZYIA4XVaU1o7bu1tezUADM8h8U7uq7YWLwt+1Rk=,iv:A23+aaAuI7m76lkuObU6/1o4TLa737iF+GLYyEkhQRk=,tag:Ig9paezE3JugJqdV0gkQFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1443hjwkj796rl8fuzsjq8ucjju8gj9f4gjnvgqhsa43hvvvm3ucqfklza9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTDlYU2FVZjJ0N2daYUQy
            ZDBqTGpQVloxcXIxSnNJdmRvckpkWHZyL0dvCjg1YS9qVFF0R0ZQaFY2bmNKcTJ4
            WFA1ZFJobnZmQVBSZk82YW1zSGpJck0KLS0tIEVvRCszRW9UcEZhUVA1aHhxMk1U
            QS8vY1FzNDMzbXFpZCt5eE1KekxObkEKR+YnLhPm4NnCZSFLY804NBVNu7pc/Y1O
            dAIoiR5/GKR7EtCN3ITccJN4uuT5UcYBYEh2L5wHDEHrJ7DABAOoTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-04T12:19:28Z"
    mac: ENC[AES256_GCM,data:ZDyaHhT5xTjBjdL6R/VOgYH1qE5aW7xHSa47fUSZ/aoYKXwa3GSwI+DLgKHXao2v3HM8ohKf6Vjc5Q7joFlSC4yyywdjdBxVr1I482Y0bC0gfEe5p50/IJJdxcKmS4somSSpBpiFjgYtYgL+UD95qyL3qzzzqwM7TmigeRCnxuI=,iv:NvKLzaWi67tfskpo4NuyPOe+zMw+D8zwL8RXwuycz9s=,tag:8E+ZtbkSDZtnAjP0ON4C7Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
