preload = /home/mx/.config/wallpapers/1490583506468.png
#preload = /home/mx/.config/wallpapers/surface-pro-7.jpg
wallpaper = eDP-1,/home/mx/.config/wallpapers/1490583506468.png
#wallpaper = ,/home/mx/.config/wallpapers/surface-pro-7.jpg
