{
  imports = [
    ./alacritty.nix
    ./atuin.nix
    ./bat.nix
    ./btop.nix
    ./chromium.nix
    ./eza.nix
    ./fuzzel.nix
    ./fzf.nix
    ./git.nix
    ./gnupg.nix
    ./less.nix
    ./mako.nix
    ./mullvad.nix
    ./password-store.nix
    ./ssh.nix
    ./starship.nix
    ./swaylock.nix
    ./tealdeer.nix
    ./thunar.nix
    ./thunderbird.nix
    ./vscode.nix
    ./waybar.nix
    ./zoxide.nix
    ./zsh.nix
  ];
}
